apiVersion: apps/v1
kind: Deployment
metadata:
  name: xray-deployment
  labels:
    app: xray
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xray
  template:
    metadata:
      labels:
        app: xray
    spec:
      containers:
      - name: xray
        image: sonnaraon/tekton-sample-repository:b106bc30785a4f8ba2633db6e7c8bef05fcd7035
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: AWS_XRAY_DAEMON_ADDRESS 
          value: xray-service:2000
---
apiVersion: v1
kind: Service
metadata:
  name: xray
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /healthcheck
spec:
  selector:
    app: xray
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: xray-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-04c293813f7f4fb3a,subnet-060c17b22c06468b1
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: xray
          servicePort: 8080
        path: /*
